language: node_js
sudo: false
node_js:
- node
services:
- mysql
install:
- npm install
before_script:
- curl -L -O http://downloads.mysql.com/docs/sakila-db.tar.gz && tar -xzf sakila-db.tar.gz
- sed -i 's/ENGINE=InnoDB/ENGINE=MyISAM/g' sakila-schema.sql
- mysql -u root < sakila-db/sakila-schema.sql
- mysql -u root < sakila-db/sakila-data.sql
script:
- npm test
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js