name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup MySQL
      run: |
        curl -L -O http://downloads.mysql.com/docs/sakila-db.tar.gz && tar -xzf sakila-db.tar.gz
        sed -i 's/ENGINE=InnoDB/ENGINE=MyISAM/g' sakila-db/sakila-schema.sql
        mysql -u root --password="root" < sakila-db/sakila-schema.sql
        mysql -u root --password="root" < sakila-db/sakila-data.sql
    - name: npm install, test, and coverage
      run: |
        npm ci
        npm test
        npm run coverage
    - uses: actions/upload-artifact@v1
      with:
        name: Coverage ${{ matrix.node-version }}
        path: coverage.lcov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
